In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [28]:
df = pd.read_csv(
    "../data/raw/jan to may police violation_anonymized791b166.csv"
)

df.head()

,id,latitude,longitude,location,vehicle_number,vehicle_type,description,violation_type,offence_code,created_datetime,...,center_code,police_station,data_sent_to_scita,junction_name,action_taken_timestamp,data_sent_to_scita_timestamp,updated_vehicle_number,updated_vehicle_type,validation_status,validation_timestamp
0,FKID000000,12.925557,77.618665,"18th Main Road, Block 2, Koramangala, Bengalur...",FKN00GL0000,CAR,NaN,"[""WRONG PARKING"",""PARKING NEAR ROAD CROSSING""]","[112,104]",2023-11-20 00:28:46+00,...,9.0,Madiwala,True,No Junction,NaN,NaN,FKN00GL0000,MAXI-CAB,approved,2023-11-30 03:08:24.818+00
1,FKID000001,12.905463,77.700778,"Sarjapura Main Road, The Grove, Janatha Colony...",FKN00GL0001,CAR,NaN,"[""NO PARKING""]",[113],2023-11-24 22:46:46+00,...,82.0,Bellandur,False,No Junction,NaN,NaN,NaN,NaN,NaN,NaN
2,FKID000002,12.925449,77.618504,"Koramangala 2nd Block, Kormangala West, Bengal...",FKN00GL0002,CAR,NaN,"[""WRONG PARKING"",""PARKING IN A MAIN ROAD""]","[112,107]",2023-11-20 00:27:46+00,...,9.0,Madiwala,True,No Junction,NaN,NaN,FKN00GL0002,MAXI-CAB,approved,2023-11-30 03:08:56.998+00
3,FKID000003,12.956521,77.518618,"6th Cross Road, Manasa Layout, Nagarbhavi, Ben...",FKN00GL0003,SCOOTER,NaN,"[""NO PARKING""]",[113],2023-11-16 06:47:46+00,...,26.0,Byatarayanapura,True,No Junction,NaN,NaN,FKN00GL0003,SCOOTER,approved,2023-11-18 23:35:12.428+00
4,FKID000004,12.977767,77.580545,"Kalidasa Road, Gandhinagar, Nehru Nagar, Benga...",FKN00GL0004,TANKER,NaN,"[""NO PARKING""]",[113],2023-11-22 04:56:46+00,...,3.0,Upparpet,True,BTP044 - Sagar Theatre Junction,NaN,NaN,FKN00GL0004,TANKER,approved,2023-11-30 03:11:32.796+00

In [29]:
df.shape

(298450, 24)

In [30]:
df.columns

Index(['id', 'latitude', 'longitude', 'location', 'vehicle_number',
       'vehicle_type', 'description', 'violation_type', 'offence_code',
       'created_datetime', 'closed_datetime', 'modified_datetime', 'device_id',
       'created_by_id', 'center_code', 'police_station', 'data_sent_to_scita',
       'junction_name', 'action_taken_timestamp',
       'data_sent_to_scita_timestamp', 'updated_vehicle_number',
       'updated_vehicle_type', 'validation_status', 'validation_timestamp'],
      dtype='str')

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 298450 entries, 0 to 298449
Data columns (total 24 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   id                            298450 non-null  str
 1   latitude                      298450 non-null  float64
 2   longitude                     298450 non-null  float64
 3   location                      295409 non-null  str
 4   vehicle_number                298450 non-null  str
 5   vehicle_type                  298450 non-null  str
 6   description                   0 non-null       float64
 7   violation_type                298450 non-null  str
 8   offence_code                  298450 non-null  str
 9   created_datetime              298450 non-null  str
 10  closed_datetime               0 non-null       float64
 11  modified_datetime             298450 non-null  str
 12  device_id                     298450 non-null  str
 13  created_by_id                 298445 non-null  str
 14  center_code                   287190 non-null  float64
 15  police_station                298445 non-null  str
 16  data_sent_to_scita            298450 non-null  bool
 17  junction_name                 298445 non-null  str
 18  action_taken_timestamp        0 non-null       float64
 19  data_sent_to_scita_timestamp  42161 non-null   str
 20  updated_vehicle_number        173196 non-null  str
 21  updated_vehicle_type          173196 non-null  str
 22  validation_status             173196 non-null  str
 23  validation_timestamp          173196 non-null  str
dtypes: bool(1), float64(6), str(17)
memory usage: 52.7 MB

In [32]:
df.isnull().sum()

id                                   0
latitude                             0
longitude                            0
location                          3041
vehicle_number                       0
vehicle_type                         0
description                     298450
violation_type                       0
offence_code                         0
created_datetime                     0
closed_datetime                 298450
modified_datetime                    0
device_id                            0
created_by_id                        5
center_code                      11260
police_station                       5
data_sent_to_scita                   0
junction_name                        5
action_taken_timestamp          298450
data_sent_to_scita_timestamp    256289
updated_vehicle_number          125254
updated_vehicle_type            125254
validation_status               125254
validation_timestamp            125254
dtype: int64

In [33]:
df.duplicated().sum()

np.int64(0)

In [34]:
df.columns = (
    df.columns
    .str.lower()
    .str.strip()
    .str.replace(" ", "_")
)

df.columns

Index(['id', 'latitude', 'longitude', 'location', 'vehicle_number',
       'vehicle_type', 'description', 'violation_type', 'offence_code',
       'created_datetime', 'closed_datetime', 'modified_datetime', 'device_id',
       'created_by_id', 'center_code', 'police_station', 'data_sent_to_scita',
       'junction_name', 'action_taken_timestamp',
       'data_sent_to_scita_timestamp', 'updated_vehicle_number',
       'updated_vehicle_type', 'validation_status', 'validation_timestamp'],
      dtype='str')

In [35]:
df = df.drop_duplicates()

df.shape

(298450, 24)

In [36]:
df.head()

,id,latitude,longitude,location,vehicle_number,vehicle_type,description,violation_type,offence_code,created_datetime,...,center_code,police_station,data_sent_to_scita,junction_name,action_taken_timestamp,data_sent_to_scita_timestamp,updated_vehicle_number,updated_vehicle_type,validation_status,validation_timestamp
0,FKID000000,12.925557,77.618665,"18th Main Road, Block 2, Koramangala, Bengalur...",FKN00GL0000,CAR,NaN,"[""WRONG PARKING"",""PARKING NEAR ROAD CROSSING""]","[112,104]",2023-11-20 00:28:46+00,...,9.0,Madiwala,True,No Junction,NaN,NaN,FKN00GL0000,MAXI-CAB,approved,2023-11-30 03:08:24.818+00
1,FKID000001,12.905463,77.700778,"Sarjapura Main Road, The Grove, Janatha Colony...",FKN00GL0001,CAR,NaN,"[""NO PARKING""]",[113],2023-11-24 22:46:46+00,...,82.0,Bellandur,False,No Junction,NaN,NaN,NaN,NaN,NaN,NaN
2,FKID000002,12.925449,77.618504,"Koramangala 2nd Block, Kormangala West, Bengal...",FKN00GL0002,CAR,NaN,"[""WRONG PARKING"",""PARKING IN A MAIN ROAD""]","[112,107]",2023-11-20 00:27:46+00,...,9.0,Madiwala,True,No Junction,NaN,NaN,FKN00GL0002,MAXI-CAB,approved,2023-11-30 03:08:56.998+00
3,FKID000003,12.956521,77.518618,"6th Cross Road, Manasa Layout, Nagarbhavi, Ben...",FKN00GL0003,SCOOTER,NaN,"[""NO PARKING""]",[113],2023-11-16 06:47:46+00,...,26.0,Byatarayanapura,True,No Junction,NaN,NaN,FKN00GL0003,SCOOTER,approved,2023-11-18 23:35:12.428+00
4,FKID000004,12.977767,77.580545,"Kalidasa Road, Gandhinagar, Nehru Nagar, Benga...",FKN00GL0004,TANKER,NaN,"[""NO PARKING""]",[113],2023-11-22 04:56:46+00,...,3.0,Upparpet,True,BTP044 - Sagar Theatre Junction,NaN,NaN,FKN00GL0004,TANKER,approved,2023-11-30 03:11:32.796+00

In [37]:
df = df.drop(
    columns=[
        "description",
        "closed_datetime",
        "action_taken_timestamp"
    ]
)

df.shape

(298450, 21)

In [38]:
df["location"] = df["location"].fillna("Unknown")

In [39]:
df["police_station"] = (
    df["police_station"]
    .fillna("Unknown")
)

In [40]:
df["junction_name"] = (
    df["junction_name"]
    .fillna("Unknown")
)

In [41]:
df.isnull().sum()

id                                   0
latitude                             0
longitude                            0
location                             0
vehicle_number                       0
vehicle_type                         0
violation_type                       0
offence_code                         0
created_datetime                     0
modified_datetime                    0
device_id                            0
created_by_id                        5
center_code                      11260
police_station                       0
data_sent_to_scita                   0
junction_name                        0
data_sent_to_scita_timestamp    256289
updated_vehicle_number          125254
updated_vehicle_type            125254
validation_status               125254
validation_timestamp            125254
dtype: int64

In [42]:
df["created_datetime"] = pd.to_datetime(
    df["created_datetime"],
    format="mixed",
    utc=True
)

In [43]:
df["created_datetime"].head()

0   2023-11-20 00:28:46+00:00
1   2023-11-24 22:46:46+00:00
2   2023-11-20 00:27:46+00:00
3   2023-11-16 06:47:46+00:00
4   2023-11-22 04:56:46+00:00
Name: created_datetime, dtype: datetime64[us, UTC]

In [44]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 298450 entries, 0 to 298449
Data columns (total 21 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   id                            298450 non-null  str
 1   latitude                      298450 non-null  float64
 2   longitude                     298450 non-null  float64
 3   location                      298450 non-null  str
 4   vehicle_number                298450 non-null  str
 5   vehicle_type                  298450 non-null  str
 6   violation_type                298450 non-null  str
 7   offence_code                  298450 non-null  str
 8   created_datetime              298450 non-null  datetime64[us, UTC]
 9   modified_datetime             298450 non-null  str
 10  device_id                     298450 non-null  str
 11  created_by_id                 298445 non-null  str
 12  center_code                   287190 non-null  float64
 13  police_station                298450 non-null  str
 14  data_sent_to_scita            298450 non-null  bool
 15  junction_name                 298450 non-null  str
 16  data_sent_to_scita_timestamp  42161 non-null   str
 17  updated_vehicle_number        173196 non-null  str
 18  updated_vehicle_type          173196 non-null  str
 19  validation_status             173196 non-null  str
 20  validation_timestamp          173196 non-null  str
dtypes: bool(1), datetime64[us, UTC](1), float64(3), str(16)
memory usage: 45.8 MB

In [46]:
#Extracting the hr in the date
df["hour"] = df["created_datetime"].dt.hour

In [47]:
df[["created_datetime","hour"]].head()

           created_datetime  hour
0 2023-11-20 00:28:46+00:00     0
1 2023-11-24 22:46:46+00:00    22
2 2023-11-20 00:27:46+00:00     0
3 2023-11-16 06:47:46+00:00     6
4 2023-11-22 04:56:46+00:00     4

In [49]:
#Day of the week
df["day_of_week"] = (
    df["created_datetime"]
    .dt.day_name()
)

In [50]:
df["day_of_week"].value_counts()

day_of_week
Sunday       46865
Saturday     43427
Wednesday    43067
Tuesday      42930
Friday       41702
Thursday     41528
Monday       38931
Name: count, dtype: int64

In [52]:
#Month
df["month"] = (
    df["created_datetime"]
    .dt.month
)

In [54]:
#Weekend
df["is_weekend"] = (
    df["created_datetime"]
    .dt.dayofweek >= 5
)

In [55]:
#Understanding peak hours
def get_time_period(hour):

    if 6 <= hour < 12:
        return "Morning"

    elif 12 <= hour < 17:
        return "Afternoon"

    elif 17 <= hour < 21:
        return "Evening Peak"

    else:
        return "Night"


df["time_period"] = (
    df["hour"]
    .apply(get_time_period)
)

In [56]:
df["time_period"].value_counts()

time_period
Night           218047
Morning          54294
Evening Peak     25336
Afternoon          773
Name: count, dtype: int64

In [57]:
#Vehicle type distribution
df["vehicle_type"].value_counts()

vehicle_type
SCOOTER                94856
CAR                    88870
MOTOR CYCLE            40811
PASSENGER AUTO         37813
MAXI-CAB               11372
LGV                     8255
GOODS AUTO              2934
MOPED                   2199
PRIVATE BUS             1633
VAN                     1466
TEMPO                   1368
BUS (BMTC/KSRTC)        1281
HGV                     1144
LORRY/GOODS VEHICLE     1122
JEEP                     913
OTHERS                   895
TOURIST BUS              379
SCHOOL VEHICLE           378
TANKER                   260
FACTORY BUS              238
MINI LORRY               199
TRACTOR                   64
Name: count, dtype: int64

In [61]:
#Vehicle impact score
vehicle_weights = {

    # two wheelers - low blockage
    "SCOOTER": 1,
    "MOTOR CYCLE": 1,
    "MOPED": 1,


    # medium vehicles
    "CAR": 3,
    "PASSENGER AUTO": 3,
    "GOODS AUTO": 3,
    "JEEP": 3,
    "VAN": 3,


    # commercial medium-heavy
    "MAXI-CAB": 4,
    "LGV": 4,
    "TEMPO": 4,


    # heavy vehicles
    "PRIVATE BUS": 5,
    "BUS (BMTC/KSRTC)": 5,
    "TOURIST BUS": 5,
    "SCHOOL VEHICLE": 5,
    "FACTORY BUS": 5,
    "HGV": 5,
    "LORRY/GOODS VEHICLE": 5,
    "TANKER": 5,
    "MINI LORRY": 5,
    "TRACTOR": 5,

    "OTHERS": 2
}


df["vehicle_impact"] = (
    df["vehicle_type"]
    .map(vehicle_weights)
)

In [62]:
df[["vehicle_type","vehicle_impact"]].head(20)

      vehicle_type  vehicle_impact
0              CAR               3
1              CAR               3
2              CAR               3
3          SCOOTER               1
4           TANKER               5
5          SCOOTER               1
6          SCOOTER               1
7          SCOOTER               1
8   PASSENGER AUTO               3
9          SCOOTER               1
10             CAR               3
11             CAR               3
12             CAR               3
13  PASSENGER AUTO               3
14         SCOOTER               1
15         SCOOTER               1
16         SCOOTER               1
17         SCOOTER               1
18         SCOOTER               1
19         SCOOTER               1

In [63]:
df["vehicle_impact"].isnull().sum()

np.int64(0)

In [64]:
df["violation_type"].value_counts()

violation_type
["WRONG PARKING"]                                                                                                                                                                                                              138764
["NO PARKING"]                                                                                                                                                                                                                 119576
["PARKING IN A MAIN ROAD","WRONG PARKING"]                                                                                                                                                                                       9472
["PARKING IN A MAIN ROAD","NO PARKING"]                                                                                                                                                                                          4818
["WRONG PARKING","DEFECTIVE NUMBER PLATE"]                                                                                                                                                                                       3317
                                                                                                                                                                                                                                ...
["PARKING IN A MAIN ROAD","PARKING NEAR TRAFFIC LIGHT OR ZEBRA CROSS","PARKING NEAR ROAD CROSSING","WRONG PARKING","NO PARKING","REFUSE TO GO FOR HIRE"]                                                                            1
["WRONG PARKING","NO PARKING","DOUBLE PARKING","PARKING OPPOSITE TO ANOTHER PARKED VEHICLE","PARKING IN A MAIN ROAD","PARKING NEAR BUSTOP/SCHOOL/HOSPITAL ETC"]                                                                     1
["WRONG PARKING","DOUBLE PARKING","PARKING NEAR BUSTOP/SCHOOL/HOSPITAL ETC","PARKING IN A MAIN ROAD"]                                                                                                                               1
["PARKING IN A MAIN ROAD","PARKING OPPOSITE TO ANOTHER PARKED VEHICLE","DOUBLE PARKING","PARKING NEAR BUSTOP/SCHOOL/HOSPITAL ETC","WRONG PARKING","NO PARKING","DEFECTIVE NUMBER PLATE","USING BLACK FILM/OTHER MATERIALS"]         1
["WRONG PARKING","PARKING NEAR BUSTOP/SCHOOL/HOSPITAL ETC","DOUBLE PARKING","PARKING OPPOSITE TO ANOTHER PARKED VEHICLE","PARKING IN A MAIN ROAD"]                                                                                  1
Name: count, Length: 991, dtype: int64

In [66]:
#Adding violation count
df["violation_count"] = (
    df["violation_type"]
    .str.count(",") + 1
)

In [67]:
df[
    ["violation_type", "violation_count"]
].head(20)

                                    violation_type  violation_count
0   ["WRONG PARKING","PARKING NEAR ROAD CROSSING"]                2
1                                   ["NO PARKING"]                1
2       ["WRONG PARKING","PARKING IN A MAIN ROAD"]                2
3                                   ["NO PARKING"]                1
4                                   ["NO PARKING"]                1
5                                   ["NO PARKING"]                1
6                                   ["NO PARKING"]                1
7                                ["WRONG PARKING"]                1
8                                   ["NO PARKING"]                1
9                                   ["NO PARKING"]                1
10                               ["WRONG PARKING"]                1
11                               ["WRONG PARKING"]                1
12                                  ["NO PARKING"]                1
13                                  ["NO PARKING"]                1
14                                  ["NO PARKING"]                1
15                                  ["NO PARKING"]                1
16                                  ["NO PARKING"]                1
17                                  ["NO PARKING"]                1
18                                  ["NO PARKING"]                1
19                               ["WRONG PARKING"]                1

In [70]:
# Road obstruction impact caused by violation type
def calculate_obstruction_score(x):

    score = 1

    if "WRONG PARKING" in x:
        score += 1

    if "NO PARKING" in x:
        score += 2

    if "PARKING IN A MAIN ROAD" in x:
        score += 5

    if "PARKING NEAR ROAD CROSSING" in x:
        score += 6

    if "PARKING NEAR TRAFFIC LIGHT" in x:
        score += 6

    if "PARKING NEAR BUSTOP" in x:
        score += 5

    if "DOUBLE PARKING" in x:
        score += 7

    return score


df["obstruction_score"] = (
    df["violation_type"]
    .apply(calculate_obstruction_score)
)

In [71]:
df[
[
"violation_type",
"obstruction_score"
]
].sort_values(
    "obstruction_score",
    ascending=False
).head(10)

                                           violation_type  obstruction_score
230500  ["NO PARKING","WRONG PARKING","DEFECTIVE NUMBE...                 33
20315   ["NO PARKING","WRONG PARKING","PARKING NEAR BU...                 33
257571  ["PARKING IN A MAIN ROAD","PARKING NEAR TRAFFI...                 33
65487   ["NO PARKING","WRONG PARKING","PARKING NEAR BU...                 33
169990  ["PARKING IN A MAIN ROAD","PARKING NEAR ROAD C...                 33
258665  ["NO PARKING","WRONG PARKING","PARKING NEAR BU...                 33
1115    ["NO PARKING","WRONG PARKING","PARKING NEAR BU...                 33
65296   ["WRONG PARKING","NO PARKING","PARKING NEAR BU...                 33
7714    ["PARKING IN A MAIN ROAD","PARKING NEAR ROAD C...                 33
92648   ["PARKING NEAR BUSTOP/SCHOOL/HOSPITAL ETC","WR...                 33

In [73]:
#Time impact
def calculate_time_impact(hour):

    if 8 <= hour <= 10:
        return 5

    elif 17 <= hour <= 20:
        return 5

    elif 11 <= hour <= 16:
        return 3

    else:
        return 1


df["time_impact"] = (
    df["hour"]
    .apply(calculate_time_impact)
)

In [77]:
df["enforcement_zone"] = df["junction_name"]

df.loc[
    df["enforcement_zone"] == "No Junction",
    "enforcement_zone"
] = df["location"]

In [82]:
df["enforcement_zone"].value_counts().head(10)

enforcement_zone
BTP051 - Safina Plaza Junction                                                 15449
BTP082 - KR Market Junction                                                    11538
BTP040 - Elite Junction                                                        10718
BTP044 - Sagar Theatre Junction                                                10549
BTP211 - Central Street Junction                                                5388
BTP058 - Subbanna Junction                                                      5189
BTP027 - Modi Bridge Junction                                                   4584
BTP020 - Hosahalli Metro Station                                                4101
Unnamed Road, Begur Chikkanahalli, Bengaluru, Karnataka. Pin-562149 (India)     4090
BTP057 - Anand Rao Junction                                                     3935
Name: count, dtype: int64

In [ ]:
df = df.drop(
    columns=["location_pressure"],
    errors="ignore"
)

In [88]:
#Calculating location pressure
zone_frequency = (
    df["enforcement_zone"]
    .value_counts()
)


df["location_pressure"] = (
    df["enforcement_zone"]
    .map(zone_frequency)
)


df["location_pressure"] = (

    df["location_pressure"]  / df["location_pressure"].max() * 10
)

In [89]:
df["congestion_impact_score"] = (

    df["obstruction_score"] * 0.35

    +

    df["vehicle_impact"] * 0.25

    +

    df["time_impact"] * 0.20

    +

    df["location_pressure"] * 0.20
)


df["congestion_impact_score"] = (

    df["congestion_impact_score"]

    /

    df["congestion_impact_score"].max()

    *

    100

).round(2)

In [90]:
df[
[
"enforcement_zone",
"vehicle_type",
"hour",
"congestion_impact_score"
]
].sort_values(
    "congestion_impact_score",
    ascending=False
).head(15)

,enforcement_zone,vehicle_type,hour,congestion_impact_score
169990,"BTP001 - 10th Cross, Dr. Rajkumar Road",TANKER,20,100.00
257571,"Chord Road, World Trade Centre, Brigade Gatewa...",LORRY/GOODS VEHICLE,19,97.87
258665,"Chord Road, Orion, Brigade Gateway, Malleshwar...",LORRY/GOODS VEHICLE,0,91.88
76973,"Outer Ring Road, Doddanakundi Junction, Doddan...",HGV,2,91.83
1115,"New Horizon College Road, New Horizon College ...",PASSENGER AUTO,0,91.71
65296,"BTP127 - Sagar Hospital, Jayanagar",TEMPO,22,90.09
65487,"BTP127 - Sagar Hospital, Jayanagar",TEMPO,22,90.09
65268,"BTP127 - Sagar Hospital, Jayanagar",TEMPO,21,90.09
65299,"BTP127 - Sagar Hospital, Jayanagar",TEMPO,22,90.09
92648,"BTP127 - Sagar Hospital, Jayanagar",TEMPO,21,90.09
92649,"BTP127 - Sagar Hospital, Jayanagar",TEMPO,22,90.09
92650,"BTP127 - Sagar Hospital, Jayanagar",TEMPO,22,90.09
7714,"Gaushala Road, Doddanakundi Junction, Doddanek...",MAXI-CAB,5,90.03
129007,"Outer Ring Road, Doddanekundi, Bengaluru, Karn...",CAR,5,88.39
169022,"BTP202 - East End Main Road, Jayanagar",CAR,2,88.38

In [91]:
df.to_csv(
    "../data/processed/cleaned_parking_data.csv",
    index=False
)

In [92]:
test = pd.read_csv(
    "../data/processed/cleaned_parking_data.csv"
)

test.shape

(298450, 34)

In [93]:
test.columns

Index(['id', 'latitude', 'longitude', 'location', 'vehicle_number',
       'vehicle_type', 'violation_type', 'offence_code', 'created_datetime',
       'modified_datetime', 'device_id', 'created_by_id', 'center_code',
       'police_station', 'data_sent_to_scita', 'junction_name',
       'data_sent_to_scita_timestamp', 'updated_vehicle_number',
       'updated_vehicle_type', 'validation_status', 'validation_timestamp',
       'hour', 'day_of_week', 'month', 'is_weekend', 'time_period',
       'vehicle_impact', 'violation_count', 'violation_severity',
       'obstruction_score', 'time_impact', 'congestion_impact_score',
       'enforcement_zone', 'location_pressure'],
      dtype='str')